name: deploy to lambda
on:
  # Trigger the workflow on push request,
  # but only for the release branch
  push:
    branches:
      - release-predictions
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: predict-kaituna-flow
          run: zip -r9 handle_predictions.zip handle_predictions.py
